'use client';

import { AIEnrichment } from '@/types';
import {
  Bot,
  Calendar,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  FileText,
  Gamepad2,
  Info,
  Sparkles,
  Star,
  Target,
  Users
} from 'lucide-react';
import { useState } from 'react';

interface AIEnrichmentSectionProps {
  aiEnrichment: AIEnrichment;
}

export function AIEnrichmentSection({ aiEnrichment }: AIEnrichmentSectionProps) {
  const [showAllStudios, setShowAllStudios] = useState(false);
  const [showAllGames, setShowAllGames] = useState(false);
  const [showAllOfferings, setShowAllOfferings] = useState(false);

  if (aiEnrichment.enrichmentStatus !== 'enriched') {
    return null;
  }

  const studios = aiEnrichment.keyParticipants?.notableStudios ?? [];
  const games = aiEnrichment.keyParticipants?.featuredGames ?? [];
  const offerings = aiEnrichment.eventDetails?.offerings ?? [];

  const visibleStudios = showAllStudios ? studios : studios.slice(0, 10);
  const visibleGames = showAllGames ? games : games.slice(0, 5);
  const visibleOfferings = showAllOfferings ? offerings : offerings.slice(0, 8);

  const getGameSearchUrl = (gameName: string) => {
    const encodedName = encodeURIComponent(gameName);
    return `https://store.steampowered.com/search?term=${encodedName}`;
  };

  const getDeveloperSearchUrl = (developerName: string) => {
    const encodedName = encodeURIComponent(developerName);
    return `https://store.steampowered.com/search/?developer=${encodedName}`;
  };

  return (
    <section className="bg-gradient-to-br from-violet-950/50 to-purple-950/30 border border-violet-500/20 rounded-2xl p-5 relative overflow-hidden">
      <div className="absolute top-0 right-0 w-32 h-32 bg-violet-500/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2" />
      
      <div className="relative">
        <div className="flex items-start gap-3 mb-4">
          <div className="p-2 bg-violet-500/20 rounded-lg shrink-0">
            <Bot className="w-5 h-5 text-violet-400" />
          </div>
          <div>
            <h2 className="text-base font-semibold text-white flex items-center gap-2">
              AI-Generated Insights
              <Sparkles className="w-4 h-4 text-violet-400" />
            </h2>
            <p className="text-xs text-violet-300/70 mt-0.5">
              Auto-generated content - May contain inaccuracies
            </p>
          </div>
        </div>

        <div className="flex items-start gap-2 p-3 bg-amber-500/10 border border-amber-500/20 rounded-lg mb-4">
          <Info className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
          <p className="text-xs text-amber-200/80 leading-relaxed">
            <strong className="text-amber-300">Disclaimer:</strong> This information was automatically generated by AI and may not be accurate or up-to-date. Always verify details on the official event website before making any decisions.
          </p>
        </div>

        {aiEnrichment.overview?.description && (
          <div className="mb-4">
            <h3 className="text-sm font-medium text-violet-300 mb-2 flex items-center gap-1.5">
              <FileText className="w-3.5 h-3.5" />
              Overview
            </h3>
            <p className="text-sm text-gray-300 leading-relaxed">
              {aiEnrichment.overview.description}
            </p>
          </div>
        )}

        {aiEnrichment.overview?.objective && (
          <div className="mb-4">
            <h3 className="text-sm font-medium text-violet-300 mb-2 flex items-center gap-1.5">
              <Target className="w-3.5 h-3.5" />
              Objective
            </h3>
            <p className="text-sm text-gray-300 leading-relaxed">
              {aiEnrichment.overview.objective}
            </p>
          </div>
        )}

        {aiEnrichment.eventDetails && (
          <div className="mb-4">
            <h3 className="text-sm font-medium text-violet-300 mb-2 flex items-center gap-1.5">
              <Calendar className="w-3.5 h-3.5" />
              Event Details
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {aiEnrichment.eventDetails.currentEdition && (
                <div className="bg-white/5 rounded-lg p-2.5">
                  <p className="text-xs text-gray-500">Current Edition</p>
                  <p className="text-sm text-white">{aiEnrichment.eventDetails.currentEdition}</p>
                </div>
              )}
              {aiEnrichment.eventDetails.typicalDuration && (
                <div className="bg-white/5 rounded-lg p-2.5">
                  <p className="text-xs text-gray-500">Typical Duration</p>
                  <p className="text-sm text-white">{aiEnrichment.eventDetails.typicalDuration}</p>
                </div>
              )}
            </div>
            
            {offerings.length > 0 && (
              <div className="mt-3">
                <p className="text-xs text-gray-500 mb-2">What is Offered</p>
                <div className="flex flex-wrap gap-1.5">
                  {visibleOfferings.map((offering, index) => (
                    <span 
                      key={index}
                      className="px-2 py-1 text-xs bg-violet-500/15 text-violet-300 rounded-md border border-violet-500/20"
                    >
                      {offering}
                    </span>
                  ))}
                </div>
                {offerings.length > 8 && (
                  <button
                    onClick={() => setShowAllOfferings(!showAllOfferings)}
                    className="mt-2 flex items-center gap-1 text-xs text-violet-400 hover:text-violet-300 transition-colors"
                  >
                    {showAllOfferings ? (
                      <>
                        <ChevronUp className="w-3 h-3" />
                        Show less
                      </>
                    ) : (
                      <>
                        <ChevronDown className="w-3 h-3" />
                        Show {offerings.length - 8} more
                      </>
                    )}
                  </button>
                )}
              </div>
            )}
          </div>
        )}

        {aiEnrichment.industryContext?.significance && (
          <div className="mb-4">
            <h3 className="text-sm font-medium text-violet-300 mb-2 flex items-center gap-1.5">
              <Star className="w-3.5 h-3.5" />
              Industry Significance
            </h3>
            <p className="text-sm text-gray-300 leading-relaxed">
              {aiEnrichment.industryContext.significance}
            </p>
          </div>
        )}

        {studios.length > 0 && (
          <div className="mb-4">
            <h3 className="text-sm font-medium text-violet-300 mb-2 flex items-center gap-1.5">
              <Users className="w-3.5 h-3.5" />
              Notable Participants
            </h3>
            <div className="flex flex-wrap gap-1.5">
              {visibleStudios.map((studio, index) => (
                <a
                  key={index}
                  href={getDeveloperSearchUrl(studio)}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-2 py-1 text-xs bg-white/5 text-gray-300 rounded-md border border-white/10 hover:bg-violet-500/20 hover:text-violet-300 hover:border-violet-500/30 transition-colors inline-flex items-center gap-1 group"
                  title={`Search for ${studio} on Steam`}
                >
                  {studio}
                  <ExternalLink className="w-2.5 h-2.5 opacity-0 group-hover:opacity-100 transition-opacity" />
                </a>
              ))}
            </div>
            {studios.length > 10 && (
              <button
                onClick={() => setShowAllStudios(!showAllStudios)}
                className="mt-2 flex items-center gap-1 text-xs text-violet-400 hover:text-violet-300 transition-colors"
              >
                {showAllStudios ? (
                  <>
                    <ChevronUp className="w-3 h-3" />
                    Show less
                  </>
                ) : (
                  <>
                    <ChevronDown className="w-3 h-3" />
                    Show all {studios.length} participants
                  </>
                )}
              </button>
            )}
          </div>
        )}

        {games.length > 0 && (
          <div>
            <h3 className="text-sm font-medium text-violet-300 mb-2 flex items-center gap-1.5">
              <Gamepad2 className="w-3.5 h-3.5" />
              Featured Games
            </h3>
            <div className="grid grid-cols-1 gap-2">
              {visibleGames.map((game, index) => {
                const hasValidSteamUrl = game.steamUrl && 
                  game.steamUrl !== 'N/A' && 
                  game.steamUrl !== 'null' &&
                  game.steamUrl.startsWith('https://store.steampowered.com/app/');
                
                const steamLink = hasValidSteamUrl 
                  ? game.steamUrl 
                  : getGameSearchUrl(game.title);

                return (
                  <a
                    key={index}
                    href={steamLink!}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center justify-between p-2.5 bg-white/5 rounded-lg border border-white/5 hover:bg-violet-500/10 hover:border-violet-500/20 transition-colors group"
                  >
                    <div className="min-w-0 flex-1">
                      <p className="text-sm font-medium text-white truncate group-hover:text-violet-300 transition-colors">
                        {game.title}
                      </p>
                      <p className="text-xs text-gray-500 truncate">
                        {game.developer && game.developer !== 'N/A' ? game.developer : 'Unknown Developer'}
                        {game.genre && game.genre !== 'N/A' && ` - ${game.genre}`}
                      </p>
                    </div>
                    <div className="ml-2 p-1.5 text-blue-400 group-hover:text-blue-300 group-hover:bg-blue-500/10 rounded-lg transition-colors shrink-0">
                      <Gamepad2 className="w-4 h-4" />
                    </div>
                  </a>
                );
              })}
            </div>
            {games.length > 5 && (
              <button
                onClick={() => setShowAllGames(!showAllGames)}
                className="mt-2 w-full flex items-center justify-center gap-1 text-xs text-violet-400 hover:text-violet-300 transition-colors py-2 bg-white/5 rounded-lg hover:bg-violet-500/10"
              >
                {showAllGames ? (
                  <>
                    <ChevronUp className="w-3 h-3" />
                    Show less
                  </>
                ) : (
                  <>
                    <ChevronDown className="w-3 h-3" />
                    Show all {games.length} featured games
                  </>
                )}
              </button>
            )}
          </div>
        )}

        {aiEnrichment.enrichedAt && (
          <div className="mt-4 pt-3 border-t border-violet-500/10">
            <p className="text-xs text-gray-500 flex items-center gap-1.5">
              <Bot className="w-3 h-3" />
              AI data last updated: {new Date(aiEnrichment.enrichedAt).toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'short',
                day: 'numeric'
              })}
            </p>
          </div>
        )}
      </div>
    </section>
  );
}
